# Generated by Django 4.2 on 2023-07-18 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_albom_qoshiqchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='qoshiqchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.qoshiqchi'),
        ),
    ]
